-- Catálogo de campos de golf de México para poder anfitrionar en cualquiera
-- de ellos, con dirección/coordenadas conectadas a Google Maps.
--
-- tipo 'publico': campos públicos/turísticos/resort y semi-privados
-- (gogolf.mx + Federación Mexicana de Golf).
-- tipo 'privado': clubes de golf de membresía — el segmento al que
-- realmente aplica el intercambio de tee times entre socios.
--
-- Fuentes:
--  - gogolf.mx (API pública /api/v1/maps/all-fields/): dirección postal
--    exacta tal como la publican ellos.
--  - Federación Mexicana de Golf, mapa oficial "Campos de Golf Federados
--    en México" (Google My Maps, KML público): coordenadas exactas pero
--    sin dirección postal ni ciudad — el estado se estimó por cercanía
--    cuando el KML no lo daba, puede haber algún error puntual cerca de
--    límites estatales.
--  - Un puñado de clubes privados conocidos compilados de conocimiento
--    general (no verificados con una fuente única) — su dirección es una
--    cadena de búsqueda (nombre + ciudad + estado), no una dirección
--    postal exacta.
--
-- Corrige cualquier entrada directamente en Supabase Studio si necesitas
-- precisión exacta antes del piloto real — ver lib/data/clubs-mexico.ts,
-- la fuente de la que se generó este INSERT (también usada en el modo
-- demo y el seed de prueba).

alter table public.clubs
  add column if not exists estado text,
  add column if not exists direccion text,
  add column if not exists tipo text not null default 'privado' check (tipo in ('privado', 'publico')),
  add column if not exists latitud numeric(10, 7),
  add column if not exists longitud numeric(10, 7);

insert into public.clubs (nombre, ciudad, estado, direccion, tipo, latitud, longitud) values
  ('Club de Golf México', 'Ciudad de México', 'Ciudad de México', 'Club de Golf México, Ciudad de México, CDMX, México', 'privado', null, null),
  ('Club Campestre de la Ciudad de México', 'Ciudad de México', 'Ciudad de México', 'Club Campestre de la Ciudad de México, Tlalpan, CDMX, México', 'privado', null, null),
  ('Club de Golf Chapultepec', 'Naucalpan de Juárez', 'Estado de México', 'Club de Golf Chapultepec, Naucalpan de Juárez, Estado de México, México', 'privado', null, null),
  ('Bosque Real Country Club', 'Huixquilucan', 'Estado de México', 'Bosque Real Country Club, Huixquilucan, Estado de México, México', 'privado', null, null),
  ('Lomas Country Club', 'Huixquilucan', 'Estado de México', 'Lomas Country Club, Huixquilucan, Estado de México, México', 'privado', null, null),
  ('Club de Golf Bellavista', 'Atizapán de Zaragoza', 'Estado de México', 'Club de Golf Bellavista, Atizapán de Zaragoza, Estado de México, México', 'privado', null, null),
  ('Club de Golf La Hacienda', 'Atizapán de Zaragoza', 'Estado de México', 'Club de Golf La Hacienda, Atizapán de Zaragoza, Estado de México, México', 'privado', null, null),
  ('Club de Golf Los Encinos', 'Metepec', 'Estado de México', 'Club de Golf Los Encinos, Metepec, Estado de México, México', 'privado', null, null),
  ('Club Santa Anita', 'Tlajomulco de Zúñiga', 'Jalisco', 'Club Santa Anita, Tlajomulco de Zúñiga, Jalisco, México', 'privado', null, null),
  ('Club Campestre de Guadalajara', 'Zapopan', 'Jalisco', 'Club Campestre de Guadalajara, Zapopan, Jalisco, México', 'privado', null, null),
  ('Atlas Golf Club', 'El Salto', 'Jalisco', 'Atlas Golf Club, El Salto, Jalisco, México', 'privado', null, null),
  ('Guadalajara Country Club', 'Guadalajara', 'Jalisco', 'Guadalajara Country Club, Guadalajara, Jalisco, México', 'privado', null, null),
  ('Club Campestre de Monterrey', 'Monterrey', 'Nuevo León', 'Club Campestre de Monterrey, Monterrey, Nuevo León, México', 'privado', null, null),
  ('Valle Alto Golf Club', 'Monterrey', 'Nuevo León', 'Valle Alto Golf Club, Monterrey, Nuevo León, México', 'privado', null, null),
  ('Club Campestre Tijuana', 'Tijuana', 'Baja California', 'Club Campestre Tijuana, Tijuana, Baja California, México', 'privado', null, null),
  ('Club Campestre de Chihuahua', 'Chihuahua', 'Chihuahua', 'Club Campestre de Chihuahua, Chihuahua, Chihuahua, México', 'privado', null, null),
  ('Club Campestre de Culiacán', 'Culiacán', 'Sinaloa', 'Club Campestre de Culiacán, Culiacán, Sinaloa, México', 'privado', null, null),
  ('Club Campestre de Hermosillo', 'Hermosillo', 'Sonora', 'Club Campestre de Hermosillo, Hermosillo, Sonora, México', 'privado', null, null),
  ('Club Campestre de Mérida', 'Mérida', 'Yucatán', 'Club Campestre de Mérida, Mérida, Yucatán, México', 'privado', null, null),
  ('Yucatán Country Club', 'Mérida', 'Yucatán', 'Yucatán Country Club, Mérida, Yucatán, México', 'privado', null, null),
  ('Club Campestre de León', 'León', 'Guanajuato', 'Club Campestre de León, León, Guanajuato, México', 'privado', null, null),
  ('Club Campestre de Saltillo', 'Saltillo', 'Coahuila', 'Club Campestre de Saltillo, Saltillo, Coahuila, México', 'privado', null, null),
  ('Club Campestre de Aguascalientes', 'Aguascalientes', 'Aguascalientes', 'Club Campestre de Aguascalientes, Aguascalientes, Aguascalientes, México', 'privado', null, null),
  ('Club de Golf Santa Gertrudis', 'Orizaba', 'Veracruz', 'Avenida Oriente 18 #2331 entre Calle Independencia y Sur 45, 94340 Orizaba, Ver.', 'publico', null, null),
  ('Club Campestre Coatzacoalcos', 'Coatzacoalcos', 'Veracruz', 'Carretera antigua a Mina, Hernández Ochoa KM 5.5, Coatzacoalcos, Veracruz, C.P. 96550', 'publico', null, null),
  ('Club de Golf Villa Rica', 'Alvarado', 'Veracruz', 'Carretera Boca del Río y Antón Lizardo KM 1.5, 94290 Alvarado, Ver.', 'publico', null, null),
  ('Campestre Cocoyoc', 'Yautepec', 'Morelos', 'Boulevard Lomas Cocoyoc, 62847, Fraccionamiento Lomas de Cocoyoc, Yautepec, Mor.', 'publico', null, null),
  ('Club de Golf Xalapa', 'Xalapa', 'Veracruz', 'Carretera Xalapa-Veracruz Km 13.5, Col. Miradores del Mar, 91631 Xalapa, Ver.', 'publico', null, null),
  ('Club de Golf El Copal', 'Tlalnepantla de Baz', 'Estado de México', 'C. San José 10, San Juan Ixhuatepec, 54180 Tlalnepantla, Méx.', 'publico', null, null),
  ('Club de Golf La Purisima', 'Ixtlahuaca', 'Estado de México', 'Autopista Toluca Atlacomulco Km. 29, La Purísima, 50740 Ixtlahuaca de Rayón, Méx.', 'publico', null, null),
  ('El Tinto Golf Course', 'Puerto Morelos', 'Quintana Roo', 'Carr. Federal 307, Chetumal Km 388, 77580 Cancún, Q.R.', 'publico', null, null),
  ('Club Campestre de Mexicali', 'Mexicali', 'Baja California', 'Carretera a San Felipe KM. 2.5, Fraccionamiento Campestre, Mexicali, B.C.', 'publico', null, null),
  ('Amanali Country Club', 'Tepeji del Río de Ocampo', 'Hidalgo', 'Blvd. Amanali Carr. Tula-Tepeji KM 11.4, Tepeji del Río, Hidalgo, 42850', 'publico', null, null),
  ('El Tigre Golf Club', 'Bahía de Banderas', 'Nayarit', 'Av. Paraíso 800, Nuevo Vallarta, Nayarit', 'publico', null, null),
  ('Club de Golf Santa Fe', 'Xochitepec', 'Morelos', 'Autopista México Acapulco KM 112.5 L1 Int. A, Col. Club de Golf Santa Fe, Xochitepec, Mor.', 'publico', null, null),
  ('Club de Golf Tequisquiapan', 'Tequisquiapan', 'Querétaro', 'Cantáridas S/N, Fraccionamiento Club de Golf, 76799 Tequisquiapan, Qro.', 'publico', null, null),
  ('Club de Golf Malanquin', 'San Miguel de Allende', 'Guanajuato', 'Carretera San Miguel de Allende – Celaya s/n km 3, San Miguel de Allende, Gto.', 'publico', null, null),
  ('Riviera Cancun Golf Club', 'Benito Juárez', 'Quintana Roo', 'Blvd. Kukulcán 25.3, Zona Hotelera, 77500 Cancún, Q.R.', 'publico', null, null),
  ('Hard Rock Golf Club Riviera Maya', 'Solidaridad', 'Quintana Roo', 'Pº Xamán-Ha S/N, Playacar, 77717 Playa del Carmen, Q.R.', 'publico', null, null),
  ('Club de Golf Hacienda Soltepec', 'Huamantla', 'Tlaxcala', 'Carretera Huamantla Puebla KM 3, Ignacio Zaragoza, Tlax.', 'publico', null, null),
  ('Mandarina Golf Club', 'Compostela', 'Nayarit', 'Carretera Federal Libre KM 200, Compostela, Nay.', 'publico', null, null),
  ('Solmar Golf Links', 'Los Cabos', 'Baja California Sur', 'Carretera a Todos Santos Kilómetro 120, 23473 Cabo San Lucas, B.C.S.', 'publico', null, null),
  ('CCC Playa Palmas Country Club', 'Carmen', 'Campeche', 'KM 5 carretera Carmen - Puerto Real, Colonia Bilvalbo, 24157 Carmen, Camp.', 'publico', null, null),
  ('Cabo Real Golf Club', 'Los Cabos', 'Baja California Sur', 'Zona del interior, México 1 km 19.5, 23457 San José del Cabo, B.C.S.', 'publico', null, null),
  ('Club Campestre San José', 'Los Cabos', 'Baja California Sur', 'Lib. al Aeropuerto Km. 119, Campo de Golf Fonatur, 23405 San José del Cabo, B.C.S.', 'publico', null, null),
  ('Puerto Los Cabos Golf Course', 'Los Cabos', 'Baja California Sur', 'Paseo de los Pescadores s/n, La Playita, 23405 San José del Cabo, B.C.S.', 'publico', null, null),
  ('Las Maravillas Campo Escuela de Golf', 'Chietla', 'Puebla', 'Av. Villas de Montecarlo SN, Chietla, Pue.', 'publico', null, null),
  ('Club de Golf San Gil', 'San Juan del Río', 'Querétaro', 'Paseo del Abanico 19A, San Juan del Río, Qro.', 'publico', null, null),
  ('Bosque Real Ejecutivo', 'Naucalpan de Juárez', 'Estado de México', 'Carretera México Huixquilucan No. 180, Col. San Cristóbal Texcalucan, 52774 Naucalpan, Méx.', 'publico', null, null),
  ('Estrella del Mar Golf y Country Club', 'Mazatlán', 'Sinaloa', 'Carr. Barrón, Cam. a Isla de la Piedra km. 10 s/n, Mazatlán, Sin.', 'publico', null, null),
  ('Paraiso del Mar Golf Club', 'La Paz', 'Baja California Sur', 'Paseo de Ciruelo SN, Paraíso del Mar, La Paz, B.C.S.', 'publico', null, null),
  ('Balvanera Golf y Polo Country Club', 'Corregidora', 'Querétaro', 'Carretera Libre a Celaya KM 10, Corregidora, Qro.', 'publico', null, null),
  ('Club de Golf El Valle', 'Ocoyoacac', 'Estado de México', 'KM 32.5 carretera México - Toluca, Ocoyoacac, Méx.', 'publico', null, null),
  ('Gran Coyote Golf', 'Solidaridad', 'Quintana Roo', 'México 307 km 294, Solidaridad, 77710 Playa del Carmen, Q.R.', 'publico', null, null),
  ('Club de Golf Vista Hermosa', 'San Agustín Etla', 'Oaxaca', 'Carretera a San Agustín Etla, Supermanzana Kilómetro 5, 68247 San Sebastián Etla, Oax.', 'publico', null, null),
  ('Hotel Avandaro - Rancho Avandaro', 'Valle de Bravo', 'Estado de México', 'Carretera San Francisco de los Ranchos, Rancho Avándaro KM. 24, 51248 Rancho Avándaro Country Club, Méx.', 'publico', null, null),
  ('Hotel Avandaro - Club de Golf', 'Valle de Bravo', 'Estado de México', 'Vega del Río s/n, Avándaro, 51200 Valle de Bravo, Méx.', 'publico', null, null),
  ('Puerto Aventuras Golf y Racquet Club', 'Solidaridad', 'Quintana Roo', 'Km. 269, Carr. Federal Chetumal 5, Juárez, 77750 Puerto Aventuras, Q.R.', 'publico', null, null),
  ('Real del Bosque', 'Tula de Allende', 'Hidalgo', 'Hotel Real del Bosque, Jacaranda 122, Col. Empleados Tolteca, 42833 Tula de Allende, Hgo.', 'publico', null, null),
  ('El Cortés Golf Club', null, 'Baja California Sur', 'El Cortés Golf Club, Baja California Sur, México', 'publico', 24.2219271, -110.3029533),
  ('Punta Mita Golf Club', null, 'Nayarit', 'Punta Mita Golf Club, Nayarit, México', 'publico', 20.7706471, -105.5365643),
  ('Bajamar Golf & Resort', null, 'Baja California', 'Bajamar Golf & Resort, Baja California, México', 'publico', 32.0165661, -116.8721905),
  ('Palma Real Golf & Beach Club', null, 'Guerrero', 'Palma Real Golf & Beach Club, Guerrero, México', 'publico', 17.6548593, -101.5944486),
  ('Cabo San Lucas Country Club', null, 'Baja California Sur', 'Cabo San Lucas Country Club, Baja California Sur, México', 'publico', 22.9152188, -109.9081472),
  ('Danzante Bay Golf Club', null, 'Baja California Sur', 'Danzante Bay Golf Club, Baja California Sur, México', 'publico', 25.7155844, -111.2342107),
  ('Iberostar Cancun Golf Club', null, 'Quintana Roo', 'Iberostar Cancun Golf Club, Quintana Roo, México', 'publico', 21.063988, -86.7806424),
  ('Iberostar Playa Paraíso Golf Club', null, 'Quintana Roo', 'Iberostar Playa Paraíso Golf Club, Quintana Roo, México', 'publico', 20.7631742, -86.9662515),
  ('Moon Palace Spa & Club Golf', null, 'Quintana Roo', 'Moon Palace Spa & Club Golf, Quintana Roo, México', 'publico', 20.9885198, -86.8401399),
  ('PGA Riviera Maya', null, 'Quintana Roo', 'PGA Riviera Maya, Quintana Roo, México', 'publico', 20.3751061, -87.3399548),
  ('Playa Mujeres Golf Club', null, 'Quintana Roo', 'Playa Mujeres Golf Club, Quintana Roo, México', 'publico', 21.2581737, -86.8204333),
  ('Higuera Golf Course', null, 'Nayarit', 'Higuera Golf Course, Nayarit, México', 'publico', 20.7979513, -105.4828852),
  ('Turtle Dunes Country Club', null, 'Guerrero', 'Turtle Dunes Country Club, Guerrero, México', 'publico', 16.7896835, -99.813308),
  ('Tres Vidas Golf Club Acapulco', null, 'Guerrero', 'Tres Vidas Golf Club Acapulco, Guerrero, México', 'publico', 16.7256748, -99.7234035),
  ('Vidanta Golf Course at Vidanta Acapulco', null, 'Guerrero', 'Vidanta Golf Course at Vidanta Acapulco, Guerrero, México', 'publico', 16.7764688, -99.7918775),
  ('Mayan Palace Golf', null, 'Guerrero', 'Mayan Palace Golf, Guerrero, México', 'publico', 16.7855256, -99.7999603),
  ('Princess Golf Course - Mundo Imperial', null, 'Guerrero', 'Princess Golf Course - Mundo Imperial, Guerrero, México', 'publico', 16.7892654, -99.8145622),
  ('Vidanta Golf at Vidanta Los Cabos', null, 'Baja California Sur', 'Vidanta Golf at Vidanta Los Cabos, Baja California Sur, México', 'publico', 23.0480826, -109.7043386),
  ('Vidanta Golf Puerto Peñasco', null, 'Baja California', 'Vidanta Golf Puerto Peñasco, Baja California, México', 'publico', 31.2455856, -113.2473992),
  ('Nicklaus Design Golf Course at Vidanta Riviera Maya', null, 'Quintana Roo', 'Nicklaus Design Golf Course at Vidanta Riviera Maya, Quintana Roo, México', 'publico', 20.766515, -86.956215),
  ('The Lakes Course at Vidanta Nuevo Vallarta', null, 'Nayarit', 'The Lakes Course at Vidanta Nuevo Vallarta, Nayarit, México', 'publico', 20.6826252, -105.2813162),
  ('Vidanta Greg Norman Golf Course', null, 'Nayarit', 'Vidanta Greg Norman Golf Course, Nayarit, México', 'publico', 20.6820374, -105.2663133),
  ('Club de Golf Santa Margarita', null, 'Guanajuato', 'Club de Golf Santa Margarita, Guanajuato, México', 'publico', 20.6864193, -101.4091073),
  ('Madeiras Country Club', null, 'Ciudad de México', 'Madeiras Country Club, Ciudad de México, México', 'publico', 19.6169144, -99.2668189),
  ('El Camaleón Golf Course at Mayakoba', null, 'Quintana Roo', 'El Camaleón Golf Course at Mayakoba, Quintana Roo, México', 'publico', 20.6897606, -87.0311157),
  ('Zibatá Golf', null, 'Querétaro', 'Zibatá Golf, Querétaro, México', 'publico', 20.6825675, -100.3377151),
  ('Club de Golf y Deportivo Las Aves', null, 'Nuevo León', 'Club de Golf y Deportivo Las Aves, Nuevo León, México', 'publico', 25.7527294, -100.039566),
  ('Gary Player Signature Golf Club El Cortés', null, 'Baja California Sur', 'Gary Player Signature Golf Club El Cortés, Baja California Sur, México', 'publico', 24.2219271, -110.3029533),
  ('Country Club de Chapala', null, 'Jalisco', 'Country Club de Chapala, Jalisco, México', 'publico', 20.3354909, -103.1216892),
  ('Club Refineria Madero', null, 'Tamaulipas', 'Club Refineria Madero, Tamaulipas, México', 'publico', 22.2732222, -97.8103013),
  ('Las Cañadas Country Club', null, 'Jalisco', 'Las Cañadas Country Club, Jalisco, México', 'publico', 20.7815379, -103.370138),
  ('Coral Golf Resort', null, 'Ciudad de México', 'Coral Golf Resort, Ciudad de México, México', 'publico', 19.3411988, -98.8875966),
  ('Club de Golf Los Tabachines', null, 'Morelos', 'Club de Golf Los Tabachines, Morelos, México', 'publico', 18.8929663, -99.2173777),
  ('Club de Golf de Zacatecas', null, 'Zacatecas', 'Club de Golf de Zacatecas, Zacatecas, México', 'publico', 22.7603352, -102.5320136),
  ('Campestre el Cristo', null, 'Puebla', 'Campestre el Cristo, Puebla, México', 'publico', 18.8824893, -98.4225347),
  ('Club de Golf Pachuca', null, 'Hidalgo', 'Club de Golf Pachuca, Hidalgo, México', 'publico', 20.0777571, -98.768586),
  ('Altozano El Nuevo Colima', null, 'Colima', 'Altozano El Nuevo Colima, Colima, México', 'publico', 19.3176364, -103.6688431),
  ('La Esmeralda Country Club', null, 'Ciudad de México', 'La Esmeralda Country Club, Ciudad de México, México', 'publico', 19.7257399, -98.9325282),
  ('Club de Golf Izar', null, 'Estado de México', 'Club de Golf Izar, Estado de México, México', 'publico', 19.1675357, -100.1605002),
  ('Azul Talavera Country Club', null, 'Durango', 'Azul Talavera Country Club, Durango, México', 'publico', 25.5176111, -103.3707147),
  ('Las Cruces Golf', null, 'Nuevo León', 'Las Cruces Golf, Nuevo León, México', 'publico', 25.7956258, -100.1145491),
  ('El Bosque Country Club', null, 'Guanajuato', 'El Bosque Country Club, Guanajuato, México', 'publico', 21.1984354, -101.7221529),
  ('Puerto Cancún Golf Club', null, 'Quintana Roo', 'Puerto Cancún Golf Club, Quintana Roo, México', 'publico', 21.166603, -86.8123397),
  ('Punta Tiburón Country Club', null, 'Veracruz', 'Punta Tiburón Country Club, Veracruz, México', 'publico', 19.0649246, -96.0955649),
  ('Ciudad Del Sol Club de Golf', null, 'Nuevo León', 'Ciudad Del Sol Club de Golf, Nuevo León, México', 'publico', 25.2508052, -99.9806107),
  ('Campeche Country Club', null, 'Campeche', 'Campeche Country Club, Campeche, México', 'publico', 19.7877067, -90.6279734),
  ('Río Grande Country Club', null, 'Coahuila', 'Río Grande Country Club, Coahuila, México', 'publico', 28.5802268, -100.5227355),
  ('Marina Vallarta Golf Club', null, 'Nayarit', 'Marina Vallarta Golf Club, Nayarit, México', 'publico', 20.6678227, -105.2543331),
  ('Alquerías Club de Golf', null, 'San Luis Potosí', 'Alquerías Club de Golf, San Luis Potosí, México', 'publico', 22.0883747, -100.865095),
  ('Club Campestre de Reynosa', null, 'Tamaulipas', 'Club Campestre de Reynosa, Tamaulipas, México', 'publico', 26.1445465, -98.4110412),
  ('Paraíso Country Club', null, 'Morelos', 'Paraíso Country Club, Morelos, México', 'publico', 18.8273072, -99.2042633),
  ('El Cid Golf & Country Club', null, 'Sinaloa', 'El Cid Golf & Country Club, Sinaloa, México', 'publico', 23.2507194, -106.4555635),
  ('NAUKA', null, 'Nayarit', 'NAUKA, Nayarit, México', 'publico', 21.0940222, -105.2218504),
  ('Club Campestre Nayar', null, 'Nayarit', 'Club Campestre Nayar, Nayarit, México', 'publico', 21.5170059, -104.9344177),
  ('The Springs Golf Club', null, 'Chihuahua', 'The Springs Golf Club, Chihuahua, México', 'publico', 30.0516019, -107.5936985),
  ('Club Campestre Tampico', null, 'Tamaulipas', 'Club Campestre Tampico, Tamaulipas, México', 'privado', 22.2560297, -97.8823132),
  ('Club Campestre Nuevo Laredo', null, 'Tamaulipas', 'Club Campestre Nuevo Laredo, Tamaulipas, México', 'privado', 27.4542361, -99.4996337),
  ('Club de Golf El Socorro A.C.', null, 'Coahuila', 'Club de Golf El Socorro A.C., Coahuila, México', 'privado', 26.900987, -101.4109192),
  ('Club Campestre de Querétaro', null, 'Querétaro', 'Club Campestre de Querétaro, Querétaro, México', 'privado', 20.5695726, -100.4077776),
  ('Club Campestre Juarez', null, 'Chihuahua', 'Club Campestre Juarez, Chihuahua, México', 'privado', 31.7197289, -106.4108464),
  ('Club Campestre Celaya S.A. De C.V.', null, 'Querétaro', 'Club Campestre Celaya S.A. De C.V., Querétaro, México', 'privado', 20.5197734, -100.7899703),
  ('Club de Golf Acapulco', null, 'Guerrero', 'Club de Golf Acapulco, Guerrero, México', 'privado', 16.8556404, -99.8583755),
  ('Club Campestre de San Luis', null, 'San Luis Potosí', 'Club Campestre de San Luis, San Luis Potosí, México', 'privado', 22.1602025, -101.0077962),
  ('Club Campestre Cordobés', null, 'Veracruz', 'Club Campestre Cordobés, Veracruz, México', 'privado', 18.9137145, -96.9544649),
  ('Club de Golf Campestre de Morelia', null, 'Michoacán', 'Club de Golf Campestre de Morelia, Michoacán, México', 'privado', 19.6816559, -101.1585021),
  ('Club Campestre Victoria', null, 'Tamaulipas', 'Club Campestre Victoria, Tamaulipas, México', 'privado', 23.7631341, -99.1321943),
  ('Club Campestre Riama', null, 'Guanajuato', 'Club Campestre Riama, Guanajuato, México', 'privado', 20.5800226, -101.1864283),
  ('Club de Golf Valle Imperial', null, 'Jalisco', 'Club de Golf Valle Imperial, Jalisco, México', 'privado', 20.7825695, -103.434098),
  ('Club de Golf San Carlos S.A. de C.V.', null, 'Estado de México', 'Club de Golf San Carlos S.A. de C.V., Estado de México, México', 'privado', 19.2728669, -99.6116236),
  ('Club Deportivo Campestre Torreón', null, 'Durango', 'Club Deportivo Campestre Torreón, Durango, México', 'privado', 25.5251086, -103.4109545),
  ('Club Campestre Chiluca', null, 'Ciudad de México', 'Club Campestre Chiluca, Ciudad de México, México', 'privado', 19.544202, -99.308116),
  ('Golf club Vallescondido', null, 'Ciudad de México', 'Golf club Vallescondido, Ciudad de México, México', 'privado', 19.5614362, -99.3069786),
  ('San Francisco Country Club', null, 'Chihuahua', 'San Francisco Country Club, Chihuahua, México', 'privado', 28.6605679, -106.1331004),
  ('Club Campestre Lourdes', null, 'Nuevo León', 'Club Campestre Lourdes, Nuevo León, México', 'privado', 25.385686, -100.997168),
  ('Golf Juriquilla', null, 'Querétaro', 'Golf Juriquilla, Querétaro, México', 'privado', 20.7070972, -100.4620957),
  ('Club Campestre de Tuxtla', null, 'Chiapas', 'Club Campestre de Tuxtla, Chiapas, México', 'privado', 16.7530279, -93.1956818),
  ('Club de Golf las Fuentes', null, 'Puebla', 'Club de Golf las Fuentes, Puebla, México', 'privado', 19.0885329, -98.2336028),
  ('Club Campestre Villahermosa', null, 'Tabasco', 'Club Campestre Villahermosa, Tabasco, México', 'privado', 18.0040702, -92.9483489),
  ('Vista Verde Country Club', null, 'Puebla', 'Vista Verde Country Club, Puebla, México', 'privado', 18.4836486, -97.4084742),
  ('Missions Club Campestre', null, 'Nuevo León', 'Missions Club Campestre, Nuevo León, México', 'privado', 25.5179474, -100.1916881),
  ('Club de Golf Pulgas Pandas', null, 'Aguascalientes', 'Club de Golf Pulgas Pandas, Aguascalientes, México', 'privado', 21.9133151, -102.3004841),
  ('Club Campestre de Durango', null, 'Durango', 'Club Campestre de Durango, Durango, México', 'privado', 23.972209, -104.6607268),
  ('Club Campestre El Campanario B.C.', null, 'Querétaro', 'Club Campestre El Campanario B.C., Querétaro, México', 'privado', 20.6114335, -100.3431049),
  ('Club de Golf Malinalco', null, 'Morelos', 'Club de Golf Malinalco, Morelos, México', 'privado', 18.9877033, -99.4742137),
  ('Alamo Country Club', null, 'Querétaro', 'Alamo Country Club, Querétaro, México', 'privado', 20.552816, -100.895788),
  ('Terralta Golf & Country Club', null, 'Nuevo León', 'Terralta Golf & Country Club, Nuevo León, México', 'privado', 25.7178094, -100.6059705),
  ('Bosques Club De Golf', null, 'Ciudad de México', 'Bosques Club De Golf, Ciudad de México, México', 'privado', 19.3773933, -99.2774582),
  ('Altozano Morelia Golf Bosque Monarca', null, 'Michoacán', 'Altozano Morelia Golf Bosque Monarca, Michoacán, México', 'privado', 19.6409803, -101.1654169),
  ('Tajin Golf Club', null, 'Veracruz', 'Tajin Golf Club, Veracruz, México', 'privado', 20.4887945, -97.4915988),
  ('La Vista Country Club', null, 'Puebla', 'La Vista Country Club, Puebla, México', 'privado', 19.0082973, -98.2546344),
  ('Club Campestre de Puebla', null, 'Puebla', 'Club Campestre de Puebla, Puebla, México', 'privado', 19.0133414, -98.2334886),
  ('Balvanera Polo Golf & Country Club', null, 'Querétaro', 'Balvanera Polo Golf & Country Club, Querétaro, México', 'privado', 20.540511, -100.469651),
  ('Club de Golf Lagunas de Miralta', null, 'Tamaulipas', 'Club de Golf Lagunas de Miralta, Tamaulipas, México', 'privado', 22.3510297, -97.9007367),
  ('Gran Reserva Golf Resort & Country Club', null, 'Morelos', 'Gran Reserva Golf Resort & Country Club, Morelos, México', 'privado', 18.850645, -99.681842),
  ('Club de Golf Cañada de Santa Fe', null, 'Ciudad de México', 'Club de Golf Cañada de Santa Fe, Ciudad de México, México', 'privado', 19.3517868, -99.2694116),
  ('Country Club Mante', null, 'Tamaulipas', 'Country Club Mante, Tamaulipas, México', 'privado', 22.7123001, -98.9679139),
  ('Tres Marias Golf Club', null, 'Michoacán', 'Tres Marias Golf Club, Michoacán, México', 'privado', 19.7080802, -101.1078643),
  ('Club de Golf la Herradura', null, 'Nuevo León', 'Club de Golf la Herradura, Nuevo León, México', 'privado', 25.5657087, -100.2289548),
  ('Club de Golf Las Lomas Zapopan', null, 'Jalisco', 'Club de Golf Las Lomas Zapopan, Jalisco, México', 'privado', 20.7146649, -103.4369671),
  ('Club de Golf de Cuernavaca', null, 'Morelos', 'Club de Golf de Cuernavaca, Morelos, México', 'privado', 18.9092086, -99.2376827),
  ('La Loma Residential & Golf Club', null, 'San Luis Potosí', 'La Loma Residential & Golf Club, San Luis Potosí, México', 'privado', 22.1175543, -101.0334395),
  ('Rancho Contento Golf Course', null, 'Jalisco', 'Rancho Contento Golf Course, Jalisco, México', 'privado', 20.7120776, -103.4802156),
  ('Altozano El Nuevo Tabasco', null, 'Tabasco', 'Altozano El Nuevo Tabasco, Tabasco, México', 'privado', 17.9478094, -92.8034935),
  ('Asturian Center of Mexico Club Campestre Ecological', null, 'Morelos', 'Asturian Center of Mexico Club Campestre Ecological, Morelos, México', 'privado', 18.9750961, -98.8654535),
  ('Club de Golf EL Molino', null, 'Guanajuato', 'Club de Golf EL Molino, Guanajuato, México', 'privado', 21.2025597, -101.6950355),
  ('Bosque Real Golf Course 9 Hole Course', null, 'Ciudad de México', 'Bosque Real Golf Course 9 Hole Course, Ciudad de México, México', 'privado', 19.4318313, -99.2763061),
  ('Club de Golf La Primavera', null, 'Sinaloa', 'Club de Golf La Primavera, Sinaloa, México', 'privado', 24.7216206, -107.3919989);
-- total: 166 clubes
